from dydx3.constants import API_HOST_MAINNET
from decouple import config

MODE = "PRODUCTION"

ABORT_ALL_POSITIONS = False

FIND_COINTEGRATED = True

PLACE_TRADES = True

RESOLUTION = "1HOUR"

WINDOW = 21

# Thresholds for opening
MAX_HALF_LIFE = 24
ZSCORE_THRES = 1.5
USD_PER_TRADE = 50
USD_MIN_COLLATERAL = 2000

# Thresholds for closing
CLOSE_AT_ZSCORE_CROSS = True

ETHEREUM_ADDRESS = "0xf613080596F6fC966A6B78B62FA3BF2A232e27D5"

STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET


HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else ""

HTTP_PROVIDER_MAINNET = config("HTTP_PROVIDER_MAINNET")
HTTP_PROVIDER_TESTNET = config("HTTP_PROVIDER_TESTNET")

HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET